### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rtmx-offiziell** [discord/linked-roles-sample#31]
![image](https://github.com/discord/linked-roles-sample/assets/157174236/904767eb-6a91-439f-88ac-5b88901cf6e7)
I have done everything as described but I still get this error and need help!

**Comment by JustinBeckwith** [comment]
Greetings!  This typically happens if you have some sort of invalid value in your `.env`.  Please follow https://discord.com/developers/docs/tutorials/configuring-app-metadata-for-linked-roles#configure-your-app, double check everything in your `.env`, and let us know if you're still having problems!
